"""remove_unique email

Revision ID: 3072676c13f7
Revises: 904b268ff8db
Create Date: 2025-05-20 10:35:52.752626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3072676c13f7'
down_revision = '904b268ff8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
