"""remove_unique_constraint_from_email

Revision ID: 904b268ff8db
Revises: 
Create Date: 2025-05-20 10:33:25.318049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '904b268ff8db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
